In [3]:
import os

In [14]:
directory = "C:/Users/Parthiva/Desktop/"

In [15]:
 os.makedirs(directory)

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:/Users/Parthiva/Desktop/'

In [ ]:
>>> from sklearn.datasets import load_sample_image
>>> from sklearn.feature_extraction import image
>>> # Use the array data from the first image in this dataset:
>>> one_image = load_sample_image("china.jpg")
>>> print('Image shape: {}'.format(one_image.shape))
Image shape: (427, 640, 3)
>>> patches = image.extract_patches_2d(one_image, (2, 2))
>>> print('Patches shape: {}'.format(patches.shape))
Patches shape: (272214, 2, 2, 3)
>>> # Here are just two of these patches:
>>> print(patches[1])
[[[174 201 231]
  [174 201 231]]
 [[173 200 230]
  [173 200 230]]]
>>> print(patches[800])
[[[187 214 243]
  [188 215 244]]
 [[187 214 243]
  [188 215 244]]]

In [8]:
from sklearn.datasets import load_sample_image
from sklearn.feature_extraction import image

In [9]:
one_image = load_sample_image("E:/land-use-classification-cnn-master/jpg/sikkim")

AttributeError: Cannot find sample image: E:/land-use-classification-cnn-master/jpg/sikkim

In [10]:
import numpy as np
from patchify import patchify, unpatchify

image = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

patches = patchify(image, (2,2), step=1) # split image into 2*3 small 2*2 patches.

assert patches.shape == (2, 3, 2, 2)
reconstructed_image = unpatchify(patches, image.shape)

assert (reconstructed_image == image).all()

In [11]:
print(patches)

[[[[ 1  2]
   [ 5  6]]

  [[ 2  3]
   [ 6  7]]

  [[ 3  4]
   [ 7  8]]]


 [[[ 5  6]
   [ 9 10]]

  [[ 6  7]
   [10 11]]

  [[ 7  8]
   [11 12]]]]


In [18]:
print(reconstructed_image)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
path = "E:/land-use-classification-cnn-master/jpg"
directory = path

cat_files = os.listdir(directory)

In [6]:
from osgeo import gdal

In [7]:
# translate files from .tif to .jpeg
for file in cat_files:
    file_no_ext = file.split('.')[0] # separate file name from extension
    img_in = directory + file
    img_out = directory + file_no_ext + '.jpeg'
            
    if not os.path.exists(directory + file_no_ext + '.jpeg'):
        !gdal_translate -of JPEG $img_in $img_out -b 1 -b 2 -b 3 -scale
        if os.path.exists(img_out):
            shutil.move(img_out, directory + file_no_ext + '.jpeg')
                

ERROR 4: `E:/land-use-classification-cnn-master/.DS_Store' not recognized as a supported file format.
ERROR 4: `E:/land-use-classification-cnn-master/.gitattributes' not recognized as a supported file format.
ERROR 4: E:/land-use-classification-cnn-master/.ipynb_checkpoints: Permission denied
ERROR 4: `E:/land-use-classification-cnn-master/0_build_rgb_dataset.ipynb' not recognized as a supported file format.
ERROR 4: `E:/land-use-classification-cnn-master/1_exploratory_data_analysis.ipynb' not recognized as a supported file format.
ERROR 4: `E:/land-use-classification-cnn-master/2_cnn_model.ipynb' not recognized as a supported file format.
ERROR 4: `E:/land-use-classification-cnn-master/3_cnn_tuned.ipynb' not recognized as a supported file format.
ERROR 4: E:/land-use-classification-cnn-master/img: Permission denied
ERROR 4: E:/land-use-classification-cnn-master/interim_reports: Permission denied
ERROR 4: `E:/land-use-classification-cnn-master/labeling_land_report.pdf' not recognized a

In [13]:
from PIL import Image
path = "E:/land-use-classification-cnn-master/jpg"

In [14]:
def crop(path, input, height, width, k, page, area):
    im = Image.open(input)
    imgwidth, imgheight = im.size
    for i in range(0,imgheight,height):
        for j in range(0,imgwidth,width):
            box = (j, i, j+width, i+height)
            a = im.crop(box)
            try:
                o = a.crop(area)
                o.save(os.path.join(path,"PNG","%s" % page,"IMG-%s.png" % k))
            except:
                pass
            k +=1

In [15]:
crop("E:/land-use-classification-cnn-master/jpg", "sikkim", 64, 64, 12)

TypeError: crop() missing 2 required positional arguments: 'page' and 'area'

In [16]:
from PIL import Image
from itertools import product

In [17]:
def tile(filename, dir_in, dir_out, d):
    name, ext = os.path.splitext(filename)
    img = Image.open(os.path.join(dir_in, filename))
    w, h = img.size
    
    grid = product(range(0, h-h%d, d), range(0, w-w%d, d))
    for i, j in grid:
        box = (j, i, j+d, i+d)
        out = os.path.join(dir_out, f'{name}_{i}_{j}{ext}')
        img.crop(box).save(out)

In [20]:
import os
os.getcwd()

'C:\\Users\\Parthiva\\CNN\\LULC'

In [23]:
os.listdir()

['.ipynb_checkpoints',
 '1_Build_RGB_Dataset.ipynb',
 '2_EDA.ipynb',
 '3_CNN_Model.ipynb',
 '4_CNN_Tuning.ipynb',
 'Basic_CNN_CM.jpg',
 'Images',
 'land_use_model.h5',
 'LULC jpg.ipynb',
 'sikkim.jpg',
 'Untitled.ipynb']

In [25]:
tile("sikkim.jpg", "E:/land-use-classification-cnn-master/jpg_in", "E:/land-use-classification-cnn-master/jpg_out", 100)